[package]
name = "ergo-protocol-framework"
version = "0.1.0"
authors = ["Robert Kornacki <11645932+robkorn@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ergo-lib          = { git = "https://github.com/ergoplatform/sigma-rust", branch = "develop",  features = ["with-serde"]  }
thiserror           = "1.0.20"
ergo-offchain-utilities          = { git = "https://github.com/robkorn/ergo-utilities-rust" }